spring.application.name=wallet_service
server.port=${PORT:8081}

# ================= DB CONFIG =================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Prevent Hibernate from failing before DB connection
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# ================= DISABLE KAFKA =================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

